### ISSUE TITLE
How to use "ctrl"?

### ISSUE THREAD

**Issue by FilippoHei** [ebranlard/xdotool-for-windows#3]
When using ctrl, the tool literally prints "ctrl", so instead of copy and pasting with ctrl+c and ctrl+v, it prints ctrlC and ctrlV. Notice the capital letters (I assume the "+" sign capitalizes the letters). How can I combine two inputs?

**Comment by ebranlard** [comment]
You can try the following:
```
xdotool key "^v"
```
let me know if that works

**Comment by FilippoHei** [comment]
Works nicely! 

See also "^s" for saving with ctrl+s. Maybe you could add these kind of shortcut-translations to the readme? 

Thanks for your work!
